### ISSUE TITLE
solr prometheus exporter crashloopbackoff

### ISSUE THREAD

**Issue by vipul-06** [apache/solr-operator#497]
I have deployed solr prometheus exporter for monitoring purpose. It is running on gke but my exporter pod is gettting error of crashloopbackoff. The logs of my exporter pod are like this
INFO  - 2022-11-10 05:45:56.943; org.apache.solr.common.cloud.ConnectionManager; Waiting for client to connect to ZooKeeper
INFO  - 2022-11-10 05:45:56.991; org.apache.solr.common.cloud.ConnectionManager; zkClient has connected
INFO  - 2022-11-10 05:45:56.991; org.apache.solr.common.cloud.ConnectionManager; Client is connected to ZooKeeper
INFO  - 2022-11-10 05:45:57.003; org.apache.solr.common.cloud.ZkStateReader; Updated live nodes from ZooKeeper... (0) -> (5)
INFO  - 2022-11-10 05:45:57.021; org.apache.solr.client.solrj.impl.ZkClientClusterStateProvider; Cluster at experro-new-solrcloud-zookeeper-0.experro-new-solrcloud-zookeeper-headless.dev-backend.svc.cluster.local:2181,experro-new-solrcloud-zookeeper-1.experro-new-solrcloud-zookeeper-headless.dev-backend.svc.cluster.local:2181,experro-new-solrcloud-zookeeper-2.experro-new-solrcloud-zookeeper-headless.dev-backend.svc.cluster.local:2181,experro-new-solrcloud-zookeeper-3.experro-new-solrcloud-zookeeper-headless.dev-backend.svc.cluster.local:2181,experro-new-solrcloud-zookeeper-4.experro-new-solrcloud-zookeeper-headless.dev-backend.svc.cluster.local:2181 ready
INFO  - 2022-11-10 05:45:57.037; org.apache.solr.prometheus.exporter.SolrExporter; Starting Solr Prometheus Exporting
INFO  - 2022-11-10 05:45:57.039; org.apache.solr.prometheus.collector.SchedulerMetricsCollector; Beginning metrics collection
INFO  - 2022-11-10 05:45:57.055; org.apache.solr.prometheus.exporter.SolrExporter; Solr Prometheus Exporter is running
WARN  - 2022-11-10 05:46:00.154; org.apache.solr.prometheus.scraper.SolrScraper; Error occurred during metrics collection => org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://experro-new-solrcloud-0.experro-new-solrcloud-headless.dev-backend:8983/solr: Forbidden

org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://experro-new-solrcloud-0.experro-new-solrcloud-headless.dev-backend:8983/solr: Forbidden

request: http://experro-new-solrcloud-0.experro-new-solrcloud-headless.dev-backend:8983/solr/ylxg9u69_merchandising_rules_field_data_shard1_replica_n1/admin/ping?_stateVer_=z7rven5j_merchandising_rules_field_data:6&wt=json&version=2.2
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:681) ~[solr-solrj-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:54:42]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:266) ~[solr-solrj-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:54:42]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:248) ~[solr-solrj-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:54:42]
	at org.apache.solr.prometheus.scraper.SolrScraper.request(SolrScraper.java:117) ~[solr-prometheus-exporter-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:54:35]
	at org.apache.solr.prometheus.scraper.SolrCloudScraper.lambda$pingAllCores$1(SolrCloudScraper.java:77) ~[solr-prometheus-exporter-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:54:35]
	at org.apache.solr.prometheus.scraper.SolrScraper.lambda$null$0(SolrScraper.java:86) ~[solr-prometheus-exporter-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:54:35]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:218) ~[solr-solrj-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:54:42]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
WARN  - 2022-11-10 05:46:00.174; org.apache.solr.prometheus.scraper.SolrScraper; Error occurred during metrics collection => org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://experro-new-solrcloud-0.experro-new-solrcloud-headless.dev-backend:8983/solr: Forbidden

org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://experro-new-solrcloud-0.experro-new-solrcloud-headless.dev-backend:8983/solr: Forbidden

request: http://experro-new-solrcloud-0.experro-new-solrcloud-headless.dev-backend:8983/solr/ylxg9u69_merchandising_rules_field_data_shard2_replica_n10/admin/ping?_stateVer_=z7rven5j_merchandising_rules_field_data:6&wt=json&version=2.2
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:681) ~[solr-solrj-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:54:42]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:266) ~[solr-solrj-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:54:42]
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:248) ~[solr-solrj-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:54:42]
	at org.apache.solr.prometheus.scraper.SolrScraper.request(SolrScraper.java:117) ~[solr-prometheus-exporter-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:54:35]
	at org.apache.solr.prometheus.scraper.SolrCloudScraper.lambda$pingAllCores$1(SolrCloudScraper.java:77) ~[solr-prometheus-exporter-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:54:35]
	at org.apache.solr.prometheus.scraper.SolrScraper.lambda$null$0(SolrScraper.java:86) ~[solr-prometheus-exporter-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:54:35]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:218) ~[solr-solrj-8.9.0.jar:8.9.0 05c8a6f0163fe4c330e93775e8e91f3ab66a3f80 - mayyasharipova - 2021-06-10 17:54:42]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by HoustonPutman** [comment]
Can you share the yamls for your solrcloud and solrprometheusexporters? Hard to debug without that.

**Comment by vipul-06** [comment]
Solr is deployed through helm and exporter yaml is below here
![Screenshot from 2022-11-21 12-27-09](https://user-images.githubusercontent.com/103365093/202984902-0a363e8c-8268-4234-9e9e-c8ba1433d377.png)

**Comment by HoustonPutman** [comment]
is that the same basic auth secret that the SolrCloud is setup to use? have you changed the solrcloud security after creating the cloud? The [default roles provided by the Solr Operator](https://github.com/apache/solr-operator/blob/v0.6.0/controllers/util/solr_security_util.go#L354) should allow for calling the ping handler. 

Can you check your solr cloud security json and see if the user in that basic auth secret is allowed to use the ping handler?

**Comment by fliphess** [comment]
I ran into a similar issue where the prometheus exporter kept crashing: Changing the CPU limits on the prometheus exporter did the trick for me: Otherwise every collection round it crashes because it's being throttled by the CPU.

**Comment by janhoy** [comment]
Answer provided, closing
